services:
  open-webui:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: open-webui-grants
    volumes:
      - ./backend:/app/backend
      - ./uos_grants:/app/uos_grants
      - ./src:/app/src
    ports:
      - "80:8080"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/uos_grants
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - shared-net

  postgres:
    image: postgres:15
    container_name: postgres-grants
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uos_grants
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - shared-net

  vectordb:
    image: pgvector/pgvector:pg16
    container_name: vectordb-grants
    environment:
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
      POSTGRES_DB: langchain
    ports:
      - "6024:5432"
    volumes:
      - vectordb:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - shared-net

volumes:
  postgres_data:
  vectordb:

networks:
  shared-net:
    driver: bridge
