FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libxml2-dev \
    libxslt1-dev \
    && rm -rf /var/lib/apt/lists/*
    
RUN apt-get update && apt-get install -y netcat-openbsd && apt-get clean

COPY ./uos_grants ./uos_grants
RUN pip install -r ./uos_grants/requirements.txt
RUN pip install -e ./uos_grants

COPY ./wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

CMD ["python", "-m", "uos_grants.scheduler"]
