services:
  open-webui:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: open-webui-grants
    volumes:
      - ./backend:/app/backend
      - ./uos_grants:/app/uos_grants
      - ./src:/app/src
      - ./loaders:/app/loaders
    ports:
      - "80:8080"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/uos_grants
    env_file:
      - .env
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres-grants
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uos_grants
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  vectordb:
    image: pgvector/pgvector:pg16
    container_name: vectordb-grants
    environment:
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
      POSTGRES_DB: langchain
    ports:
      - "6024:5432"
    volumes:
      - vectordb:/var/lib/postgresql/data
    restart: unless-stopped

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins

volumes:
  postgres_data:
  vectordb:
