"""Recreate missing researchers table

Revision ID: 67a47aff9354
Revises: 6b6794f62349
Create Date: 2025-07-02 15:18:54.369809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67a47aff9354'
down_revision: Union[str, None] = '6b6794f62349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('main_role', sa.String(), nullable=True),
    sa.Column('additional_roles', sa.Text(), nullable=True),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.Column('research_interests', sa.Text(), nullable=True),
    sa.Column('last_response', sa.String(), nullable=False),
    sa.Column('last_modified', sa.String(), nullable=True),
    sa.Column('last_scraped', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_researcher_url')
    )
    op.create_index(op.f('ix_researchers_id'), 'researchers', ['id'], unique=False)
    op.create_index(op.f('ix_researchers_url'), 'researchers', ['url'], unique=True)
    op.create_table('staff_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('last_response', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_staff_urls_id'), 'staff_urls', ['id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_urls_id'), table_name='staff_urls')
    op.drop_table('staff_urls')
    op.drop_index(op.f('ix_researchers_url'), table_name='researchers')
    op.drop_index(op.f('ix_researchers_id'), table_name='researchers')
    op.drop_table('researchers')
    # ### end Alembic commands ###
