"""Modified researcher table

Revision ID: 6b6794f62349
Revises: 622cef9a393d
Create Date: 2025-06-27 11:48:06.609026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b6794f62349'
down_revision: Union[str, None] = '622cef9a393d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researchers', sa.Column('last_modified', sa.String(), nullable=True))
    op.add_column('researchers', sa.Column('last_scraped', sa.DateTime(), nullable=True))
    op.alter_column('researchers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('researchers', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('researchers_url_key', 'researchers', type_='unique')
    op.create_index(op.f('ix_researchers_url'), 'researchers', ['url'], unique=True)
    op.create_unique_constraint('uq_researcher_url', 'researchers', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_researcher_url', 'researchers', type_='unique')
    op.drop_index(op.f('ix_researchers_url'), table_name='researchers')
    op.create_unique_constraint('researchers_url_key', 'researchers', ['url'])
    op.alter_column('researchers', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('researchers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('researchers', 'last_scraped')
    op.drop_column('researchers', 'last_modified')
    # ### end Alembic commands ###
